# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mecz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name=b'data published')),
                ('bramki_gospodarz', models.IntegerField(default=0)),
                ('bramki_gosc', models.IntegerField(default=0)),
                ('kolejka', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Mecze',
            },
        ),
        migrations.CreateModel(
            name='TypZdarzenia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Akcja',
            },
        ),
        migrations.CreateModel(
            name='Zawodnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('pozycja', models.CharField(max_length=50)),
                ('data_urodzenia', models.DateField(verbose_name=b'data published')),
            ],
            options={
                'verbose_name_plural': 'Zawodnicy',
            },
        ),
        migrations.CreateModel(
            name='Zdarzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuta', models.IntegerField(default=0)),
                ('mecz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Mecz')),
                ('typ_zdarzenia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.TypZdarzenia')),
                ('zawodnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zawodnik')),
            ],
        ),
        migrations.CreateModel(
            name='Zespol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_klubu', models.CharField(max_length=50)),
                ('trener', models.CharField(max_length=50)),
                ('prezes', models.CharField(max_length=50)),
                ('strona_internetowa', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Zespoly',
            },
        ),
        migrations.AddField(
            model_name='zawodnik',
            name='zespol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Zespol'),
        ),
        migrations.AddField(
            model_name='mecz',
            name='zespol_gosc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rola_goscia', to='polls.Zespol'),
        ),
        migrations.AddField(
            model_name='mecz',
            name='zespol_gospodarz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rola_gospodarza', to='polls.Zespol'),
        ),
    ]
