# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-17 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_zespol_punkty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zespol',
            name='punkty',
        ),
    ]
