# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_zespol_punkty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zdarzenie',
            options={'verbose_name_plural': 'Zdarzenie'},
        ),
    ]
