# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170518_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mecz',
            name='data',
            field=models.DateField(verbose_name=b'data rozegrania'),
        ),
        migrations.AlterField(
            model_name='zawodnik',
            name='data_urodzenia',
            field=models.DateField(verbose_name=b'data urodzenia'),
        ),
    ]
